<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Spending extends Model
{
    protected $fillable = [
        'user_id',
        'fixed_income',
        'extra_income',
        'fixed_rent_budget',
        'fixed_rent',
        'fixed_insurance_budget',
        'fixed_insurance',
        'fixed_other_budget',
        'fixed_other',
        'variable_utilities_budget',
        'variable_utilities',
        'variable_food_budget',
        'variable_food',
        'variable_daily_budget',
        'variable_daily',
        'variable_transportation_budget',
        'variable_transportation',
        'variable_automotive_budget',
        'variable_automotive',
        'variable_other_budget',
        'variable_other',
        'selfinvest_communication_budget',
        'selfinvest_communication',
        'selfinvest_education_budget',
        'selfinvest_education',
        'selfinvest_medical_budget',
        'selfinvest_medical',
        'selfinvest_clothing_budget',
        'selfinvest_clothing',
        'selfinvest_allowance_budget',
        'selfinvest_allowance',
        'selfinvest_pocketmoney_budget',
        'selfinvest_pocketmoney',
        'selfinvest_favorite_budget',
        'selfinvest_favorite',
        'selfinvest_other_budget',
        'selfinvest_other',
        'storeinvest_saving_budget',
        'storeinvest_saving',
        'storeinvest_investment_budget',
        'storeinvest_investment',
        'storeinvest_other_budget',
        'storeinvest_other',
    ];

    public static $rules = array(
        'fixed_income' => 'integer|min:0',
        'extra_income' => 'integer|min:0',
        'fixed_rent_budget' => 'integer|min:0',
        'fixed_rent' => 'integer|min:0',
        'fixed_insurance_budget' => 'integer|min:0',
        'fixed_insurance' => 'integer|min:0',
        'fixed_other_budget' => 'integer|min:0',
        'fixed_other' => 'integer|min:0',
        'variable_utilities_budget' => 'integer|min:0',
        'variable_utilities' => 'integer|min:0',
        'variable_food_budget' => 'integer|min:0',
        'variable_food' => 'integer|min:0',
        'variable_daily_budget' => 'integer|min:0',
        'variable_daily' => 'integer|min:0',
        'variable_transportation_budget' => 'integer|min:0',
        'variable_transportation' => 'integer|min:0',
        'variable_automotive_budget' => 'integer|min:0',
        'variable_automotive' => 'integer|min:0',
        'variable_other_budget' => 'integer|min:0',
        'variable_other' => 'integer|min:0',
        'selfinvest_communication_budget' => 'integer|min:0',
        'selfinvest_communication' => 'integer|min:0',
        'selfinvest_education_budget' => 'integer|min:0',
        'selfinvest_education' => 'integer|min:0',
        'selfinvest_medical_budget' => 'integer|min:0',
        'selfinvest_medical' => 'integer|min:0',
        'selfinvest_clothing_budget' => 'integer|min:0',
        'selfinvest_clothing' => 'integer|min:0',
        'selfinvest_allowance_budget' => 'integer|min:0',
        'selfinvest_allowance' => 'integer|min:0',
        'selfinvest_pocketmoney_budget' => 'integer|min:0',
        'selfinvest_pocketmoney' => 'integer|min:0',
        'selfinvest_favorite_budget' => 'integer|min:0',
        'selfinvest_favorite' => 'integer|min:0',
        'selfinvest_other_budget' => 'integer|min:0',
        'selfinvest_other' => 'integer|min:0',
        'storeinvest_saving_budget' => 'integer|min:0',
        'storeinvest_saving' => 'integer|min:0',
        'storeinvest_investment_budget' => 'integer|min:0',
        'storeinvest_investment' => 'integer|min:0',
        'storeinvest_other_budget' => 'integer|min:0',
        'storeinvest_other' => 'integer|min:0',
    );
}
