<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Spending extends Model
{
    protected $guarded = [
        'id'
    ];

    protected $attributes = [
        'user_id' => '',
        'fixed_income' => 0,
        'extra_income' => 0,
        'fixed_rent_budget' => 0,
        'fixed_rent' => 0,
        'fixed_insurance_budget' => 0,
        'fixed_insurance' => 0,
        'fixed_other_budget' => 0,
        'fixed_other' => 0,
        'variable_utilities_budget' => 0,
        'variable_utilities' => 0,
        'variable_food_budget' => 0,
        'variable_food' => 0,
        'variable_daily_budget' => 0,
        'variable_daily' => 0,
        'variable_transportation_budget' => 0,
        'variable_transportation' => 0,
        'variable_automotive_budget' => 0,
        'variable_automotive' => 0,
        'variable_other_budget' => 0,
        'variable_other' => 0,
        'selfinvest_communication_budget' => 0,
        'selfinvest_communication' => 0,
        'selfinvest_education_budget' => 0,
        'selfinvest_education' => 0,
        'selfinvest_medical_budget' => 0,
        'selfinvest_medical' => 0,
        'selfinvest_clothing_budget' => 0,
        'selfinvest_clothing' => 0,
        'selfinvest_allowance_budget' => 0,
        'selfinvest_allowance' => 0,
        'selfinvest_pocketmoney_budget' => 0,
        'selfinvest_pocketmoney' => 0,
        'selfinvest_favorite_budget' => 0,
        'selfinvest_favorite' => 0,
        'selfinvest_other_budget' => 0,
        'selfinvest_other' => 0,
        'storeinvest_saving_budget' => 0,
        'storeinvest_saving' => 0,
        'storeinvest_investment_budget' => 0,
        'storeinvest_investment' => 0,
        'storeinvest_other_budget' => 0,
        'storeinvest_other' => 0
    ];

    public static $rules = array(
        'fixed_income' => 'integer|min:0',
        'extra_income' => 'integer|min:0',
        'fixed_rent_budget' => 'integer|min:0',
        'fixed_rent' => 'integer|min:0',
        'fixed_insurance_budget' => 'integer|min:0',
        'fixed_insurance' => 'integer|min:0',
        'fixed_other_budget' => 'integer|min:0',
        'fixed_other' => 'integer|min:0',
        'variable_utilities_budget' => 'integer|min:0',
        'variable_utilities' => 'integer|min:0',
        'variable_food_budget' => 'integer|min:0',
        'variable_food' => 'integer|min:0',
        'variable_daily_budget' => 'integer|min:0',
        'variable_daily' => 'integer|min:0',
        'variable_transportation_budget' => 'integer|min:0',
        'variable_transportation' => 'integer|min:0',
        'variable_automotive_budget' => 'integer|min:0',
        'variable_automotive' => 'integer|min:0',
        'variable_other_budget' => 'integer|min:0',
        'variable_other' => 'integer|min:0',
        'selfinvest_communication_budget' => 'integer|min:0',
        'selfinvest_communication' => 'integer|min:0',
        'selfinvest_education_budget' => 'integer|min:0',
        'selfinvest_education' => 'integer|min:0',
        'selfinvest_medical_budget' => 'integer|min:0',
        'selfinvest_medical' => 'integer|min:0',
        'selfinvest_clothing_budget' => 'integer|min:0',
        'selfinvest_clothing' => 'integer|min:0',
        'selfinvest_allowance_budget' => 'integer|min:0',
        'selfinvest_allowance' => 'integer|min:0',
        'selfinvest_pocketmoney_budget' => 'integer|min:0',
        'selfinvest_pocketmoney' => 'integer|min:0',
        'selfinvest_favorite_budget' => 'integer|min:0',
        'selfinvest_favorite' => 'integer|min:0',
        'selfinvest_other_budget' => 'integer|min:0',
        'selfinvest_other' => 'integer|min:0',
        'storeinvest_saving_budget' => 'integer|min:0',
        'storeinvest_saving' => 'integer|min:0',
        'storeinvest_investment_budget' => 'integer|min:0',
        'storeinvest_investment' => 'integer|min:0',
        'storeinvest_other_budget' => 'integer|min:0',
        'storeinvest_other' => 'integer|min:0',
    );
}
